export const CHANGE_TEXT = 'CHANGE_TEXT';

export const TOGGLE_COMPLETED = 'TOGGLE_COMPLETE';
export const ADD_LABEL = 'ADD_LABEL';
export const CHANGE_LABEL = 'CHANGE_LABEL';
export const REMOVE_LABEL = 'REMOVE_LABEL';
export const ADD_MEMBER = 'ADD_MEMBER';
export const REMOVE_MEMBER = 'REMOVE_MEMBER';

export const ADD_DATE = 'ADD_DATE';
export const REMOVE_DATE = 'REMOVE_DATE';
export const CHANGE_DATE = 'CHANGE_DATE';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
export const REMOVE_DESCRIPTION = 'REMOVE_DESCRIPTION';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';

export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const REMOVE_CHECKLIST = 'REMOVE_CHECKLIST';

export const ADD_CHECKLIST_ITEM = 'ADD_CHECKLIST_ITEM';
export const REMOVE_CHECKLIST_ITEM = 'REMOVE_CHECKLIST_ITEM';
export const CHANGE_CHECKLIST_ITEM = 'CHANGE_CHECKLIST_ITEM';
